name: Generate

on:
  push:
  pull_request:

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download reggen
        run: |
          curl -L https://github.com/LiteLDev/RegistryGenerator/releases/download/v0.2.0/reggen \
            -o reggen
          chmod +x reggen

      - name: Generate index
        run: |
          ./reggen --input teeth --output docs/index.json

      - name: Copy assets
        run: |
          cp -r assets/* docs/

      - name: Generate website
        run: |
          python scripts/generate_website.py

      - name: Upload index as pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

  deploy_pages:
    name: Deploy pages
    if: github.event_name == 'push'
    needs: generate
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy pages
        uses: actions/deploy-pages@v1